### PR TITLE
Modernize crate

### PR DESCRIPTION
**Pull request by apasel422**
r? @Gankro

### CODE REVIEW

**Comment by apasel422** [comment]
Ah, `drain` isn't available on stable. I'll update the PR shortly.

**Comment by apasel422** [comment]
Updated.

**Comment by apasel422** [comment]
Ping.

**Comment by Gankra** [comment]
LGTM

**Comment by apasel422** [comment]
Thanks! Could you add `contain-rs` as an owner to this crate on crates.io?

**Comment by apasel422** [comment]
Ping.

**Comment by Gankra** [comment]
???

Trying to add publishers produces http vomit.

Trying to add owners on a lark worked... can you publish...?

**Comment by apasel422** [comment]
Yup, thanks!

**Pull request merged**
