### PR TITLE
Ungate `drain`

### PR DESCRIPTION
**Pull request by apasel422**
r? @Gankro

### CODE REVIEW

**Comment by Gankra** [comment]
Quick check: does removing a gate break anyone using that gate? iirc it's just a `#[warn]` by default, right?

**Comment by apasel422** [comment]
Hmm. Good point. I think it's currently an error in Cargo. We could leave the feature there and have it do nothing, but since the gate only worked on nightly, I'm not too concerned about the breakage. Thoughts?

**Comment by apasel422** [comment]
Presumably this will come with a version bump, anyway.

**Comment by Gankra** [comment]
This will also force anyone using this crate stabley to upgrade to the latest stable, fwiw.

**Comment by Gankra** [comment]
We could defer it to be "maximally nice", but this is a pretty niche crate.

**Comment by apasel422** [comment]
But we haven't pushed this to crates.io yet. We'll just do a major version
change before publishing.

**Comment by Gankra** [comment]
@apasel422 Yeah, sure, it's semver, I'm just wondering if we should try to go above and beyond

**Comment by Gankra** [comment]
Talking it out on IRC, seems people don't care. Ship it.

**Pull request merged**
